<?php

namespace App\Http\Controllers\Api\V1;

use App\Actions\Audit\RecordAuditEvent;
use App\Actions\Variables\PushVariables;
use App\Enums\AuditAction;
use App\Http\Controllers\Controller;
use App\Http\Requests\Api\PushVariablesRequest;
use App\Http\Resources\ReleaseResource;
use App\Http\Resources\ReleaseSummaryResource;
use App\Models\DeployToken;
use App\Models\Release;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;
use Illuminate\Http\Response;

/**
 * The endpoints a deploy server talks to.
 *
 * Everything here is scoped to the single environment the presented deploy
 * token stands for, so no request has to name a project or environment and
 * no request can be pointed at a different one.
 */
class DeployController extends Controller
{
    public function __construct(private readonly RecordAuditEvent $audit) {}

    /**
     * Get a release, defaulting to the latest one.
     */
    public function release(Request $request): ReleaseResource
    {
        return new ReleaseResource($this->resolveRelease($request));
    }

    /**
     * Get a release rendered as a .env file.
     */
    public function env(Request $request): Response
    {
        $release = $this->resolveRelease($request);
        $environment = $release->environment;

        $header = sprintf(
            "Generated by Envserver on %s\nProject %s, environment %s, release %d\nDo not edit by hand.",
            now()->toDayDateTimeString(),
            $environment->project->slug,
            $environment->slug,
            $release->version,
        );

        return response($release->toEnvFile($header), 200, [
            'Content-Type' => 'text/plain; charset=utf-8',
            'Cache-Control' => 'no-store',
        ]);
    }

    /**
     * Push a set of variables into the environment.
     *
     * Requires the env:write scope, which is opt-in per token — unlike the
     * read endpoints above, granted to every deploy token. There is no
     * personal author to record here, so the underlying variable.created and
     * variable.updated audit entries are actor-less; this event is what
     * names the token, so the trail still says who.
     */
    public function push(PushVariablesRequest $request, PushVariables $push): JsonResponse
    {
        $deployToken = $this->token($request);
        $environment = $deployToken->environment;

        $result = $push->handle($environment, $request->validated('variables'));

        $this->audit->handle(
            team: $environment->project->team,
            action: AuditAction::DeployTokenPushed,
            subject: $deployToken,
            metadata: [
                'name' => $deployToken->name,
                'project' => $environment->project->slug,
                'environment' => $environment->slug,
                'created' => $result['created'],
                'updated' => $result['updated'],
                'unchanged' => $result['unchanged'],
                'skipped' => $result['skipped'],
            ],
        );

        return response()->json(['data' => $result]);
    }

    /**
     * List the environment's release history.
     */
    public function releases(Request $request): AnonymousResourceCollection
    {
        return ReleaseSummaryResource::collection(
            $this->token($request)->environment->releases()->with('publisher')->paginate(50)
        );
    }

    /**
     * Resolve the requested release, or the latest one.
     */
    private function resolveRelease(Request $request): Release
    {
        $environment = $this->token($request)->environment;

        $release = $request->filled('version')
            ? $environment->releases()->where('version', $request->integer('version'))->first()
            : $environment->latestRelease();

        abort_if($release === null, 404, 'This environment has no published release yet.');

        return $release;
    }

    /**
     * Get the deploy token the middleware resolved for this request.
     */
    private function token(Request $request): DeployToken
    {
        return $request->attributes->get('deploy_token');
    }
}
