<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Http\Resources\ReleaseResource;
use App\Http\Resources\ReleaseSummaryResource;
use App\Models\DeployToken;
use App\Models\Release;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;
use Illuminate\Http\Response;

/**
 * The endpoints a deploy server talks to.
 *
 * Everything here is scoped to the single environment the presented deploy
 * token stands for, so no request has to name a project or environment and
 * no request can be pointed at a different one.
 */
class DeployController extends Controller
{
    /**
     * Get a release, defaulting to the latest one.
     */
    public function release(Request $request): ReleaseResource
    {
        return new ReleaseResource($this->resolveRelease($request));
    }

    /**
     * Get a release rendered as a .env file.
     */
    public function env(Request $request): Response
    {
        $release = $this->resolveRelease($request);
        $environment = $release->environment;

        $header = sprintf(
            "Generated by Envserver on %s\nProject %s, environment %s, release %d\nDo not edit by hand.",
            now()->toDayDateTimeString(),
            $environment->project->slug,
            $environment->slug,
            $release->version,
        );

        return response($release->toEnvFile($header), 200, [
            'Content-Type' => 'text/plain; charset=utf-8',
            'Cache-Control' => 'no-store',
        ]);
    }

    /**
     * List the environment's release history.
     */
    public function releases(Request $request): AnonymousResourceCollection
    {
        return ReleaseSummaryResource::collection(
            $this->token($request)->environment->releases()->with('publisher')->paginate(50)
        );
    }

    /**
     * Resolve the requested release, or the latest one.
     */
    private function resolveRelease(Request $request): Release
    {
        $environment = $this->token($request)->environment;

        $release = $request->filled('version')
            ? $environment->releases()->where('version', $request->integer('version'))->first()
            : $environment->latestRelease();

        abort_if($release === null, 404, 'This environment has no published release yet.');

        return $release;
    }

    /**
     * Get the deploy token the middleware resolved for this request.
     */
    private function token(Request $request): DeployToken
    {
        return $request->attributes->get('deploy_token');
    }
}
