<?php

use App\Support\EnvFileRenderer;
use Dotenv\Dotenv;

beforeEach(function () {
    $this->renderer = new EnvFileRenderer;
});

it('writes a plain value without quotes', function () {
    expect($this->renderer->render(['APP_ENV' => 'production']))
        ->toBe("APP_ENV=production\n");
});

it('keeps the given order', function () {
    $rendered = $this->renderer->render(['B' => '2', 'A' => '1', 'C' => '3']);

    expect($rendered)->toBe("B=2\nA=1\nC=3\n");
});

it('renders an empty value', function () {
    expect($this->renderer->render(['MAIL_PASSWORD' => '']))
        ->toBe("MAIL_PASSWORD=\n");
});

it('quotes values that would otherwise be cut short', function (string $value) {
    expect($this->renderer->render(['KEY' => $value]))->toStartWith('KEY="');
})->with([
    'space' => 'two words',
    'hash' => 'value#notacomment',
    'dollar' => 'p$ssw0rd',
    'double quote' => 'say "hi"',
    'single quote' => "it's fine",
    'backslash' => 'C:\\path\\to',
    'newline' => "line1\nline2",
    'tab' => "a\tb",
]);

it('escapes a dollar sign so it is not treated as interpolation', function () {
    expect($this->renderer->render(['KEY' => 'p$ssw0rd']))
        ->toBe("KEY=\"p\\\$ssw0rd\"\n");
});

it('collapses a newline into an escape sequence so every entry stays on one line', function () {
    $rendered = $this->renderer->render(['PRIVATE_KEY' => "-----BEGIN-----\nabc\n-----END-----"]);

    expect(substr_count($rendered, "\n"))->toBe(1);
});

it('survives a round trip through the parser Laravel actually uses', function (string $value) {
    $rendered = $this->renderer->render(['SECRET' => $value]);

    expect(Dotenv::parse($rendered)['SECRET'])->toBe($value);
})->with([
    'plain' => 'production',
    'empty' => '',
    'space' => 'two words',
    'hash' => 'value#notacomment',
    'leading hash' => '#starts-with-hash',
    'dollar' => 'p$ssw0rd',
    'braced variable' => 'literal ${APP_NAME} text',
    'double quote' => 'say "hi"',
    'single quote' => "it's fine",
    'both quotes' => 'mix "of" \'quotes\'',
    'backslash' => 'C:\\path\\to',
    'trailing backslash' => 'ends-with\\',
    'newline' => "line1\nline2",
    'crlf' => "line1\r\nline2",
    'tab' => "a\tb",
    'unicode' => 'wachtwoord-mét-ünicode-🔐',
    'dsn' => 'postgres://user:p@ss w0rd!#x@host:5432/db?sslmode=require',
    'json' => '{"key":"value","n":1}',
    'pem' => "-----BEGIN RSA PRIVATE KEY-----\nMIIEow==\n-----END RSA PRIVATE KEY-----",
    'only whitespace' => '   ',
    'equals' => 'a=b=c',
]);

it('renders a whole file that parses back to the same map', function () {
    $variables = [
        'APP_ENV' => 'production',
        'APP_DEBUG' => 'false',
        'DB_PASSWORD' => 'p$ss "word"',
        'MAIL_FROM_NAME' => 'Envserver Support',
        'EMPTY' => '',
    ];

    expect(Dotenv::parse($this->renderer->render($variables)))->toBe($variables);
});

it('can prefix the file with a header comment', function () {
    $rendered = $this->renderer->render(['A' => '1'], header: "Generated by Envserver\nDo not edit");

    expect($rendered)->toBe("# Generated by Envserver\n# Do not edit\n\nA=1\n")
        ->and(Dotenv::parse($rendered))->toBe(['A' => '1']);
});
